#!/bin/bash

check_process() {
  [ "$1" = "" ]  && return 0
  [ `pgrep -n $1` ] && return 1 || return 0
}

while [ 1 ]; do
  # timestamp
  ts=`date +%T`
  check_process "flight"
  [ $? -eq 0 ] && echo "$ts: not running, starting alternate condition..." && `./kpwm` && break
done

